version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - mvn package shade:shade
      - mv target/oms-config-service-0.1.jar .
      - unzip oms-config-service-0.1.jar
      - rm -rf target tst src buildspec.yml pom.xml oms-config-service-0.1.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  files:
    - template-export.yml